### PR TITLE
fixed currying functions that uses func_get_args()

### PR DESCRIPTION
**Pull request by webNeat**
Hello, I added this test case

``` php
public function test_curry_using_func_get_args()
{
    $fnNoArgs = C\curry(function () { return func_get_args(); });
    $this->assertEquals([], $fnNoArgs());
    $this->assertEquals([1], $fnNoArgs(1));
    $this->assertEquals([1, 2, 'three'], $fnNoArgs(1, 2, 'three'));

    $fnOneArg = C\curry(function ($x) { return func_get_args(); });
    $this->assertEquals([1], $fnNoArgs(1));
    $this->assertEquals([1, 2, 'three'], $fnNoArgs(1, 2, 'three'));

    $fnTwoArgs = C\curry(function ($x, $y) { return func_get_args(); });
    $curried = $fnTwoArgs(1);
    $this->assertEquals([1, 2], $fnNoArgs(1, 2));
    $this->assertEquals([1, 2, 'three'], $fnNoArgs(1, 2, 'three'));
    $this->assertEquals([1, 2], $curried(2));
    $this->assertEquals([1, 2, 'three'], $curried(2, 'three'));
}
```

And fixed the code to make it pass.

### CODE REVIEW

**Comment by matteosister** [comment]
any idea on why the test is failing??

Beside the fact that I simply should deprecate php 5.3 and 5.4 :smile:

**Comment by webNeat** [comment]
Well now we have

``` php
function curry($callable)
{
    if (_number_of_required_params($callable) < 2)
        return $callable;
    return _curry_array_args($callable, _rest(func_get_args()));
}
```

So in case of `$callable = array(new TestSubject(), 'identity')` it's simply returned because it has only 1 parameter. And in this case, we end up having `$identity = array(new TestSubject(), 'identity')`. So doing `$identity(1)` gives `FATAL ERROR Function name must be a string` on PHP 5.3

Here is a sample code demonstrating the issue:

``` php
<?php
class TestSubject
{
    public function identity($a) {
        return $a;
    }
}

$add = array(new TestSubject(), 'identity');

echo $add(1);
```

This code works for PHP 5.4+ but not for PHP 5.3 !

**Comment by matteosister** [comment]
:+1: merged! many thanks!

**Comment by matteosister** [comment]
a new release is coming...

**Comment by webNeat** [comment]
Thank you for merging that :smile:

**Pull request merged**
